services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olist-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./input_app/key.json:/app/input_app/key.json:ro

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: Australia/Sydney
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/project/input_app/key.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - ./logs:/opt/airflow/logs
    command: airflow standalone
